version: '3.8'

services:
  ibs_api:
    container_name: ibs_api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '3333:3333'
    volumes:
      - ./src:/usr/src/app/src
  postgres:
    container_name: ibs-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: ibs-pg
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
